In [20]:
import numpy as np 
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import pandas as pd 
from time import time

from utils import binary_classification

FEATURE_COLUMNS = ["Time", "Low", "High", "Open", "Close", "Volume"]
SEQ_LEN = 60
FORECAST_STEP = 3
BATCH_SIZE = 64
EPOCHS = 20

scaler = MinMaxScaler()
        
df = pd.read_csv("data/BTC-USD.csv", names=FEATURE_COLUMNS)
df.set_index("Time", inplace=True)
btc_df = df.copy()
btc_df["Forecast"] = btc_df["Close"].shift(-FORECAST_STEP)
btc_df["Class"] = list(map(binary_classification, btc_df["Close"], btc_df["Forecast"]))
btc_df.dropna(inplace=True)
#btc_df["Close"] = scale(btc_df["Close"].values)
#btc_df["Volume"] = scale(btc_df["Volume"].values)
btc_df.head(10)

Low         High         Open  ...    Volume     Forecast  Class
Time                                               ...                              
1528968660  6489.549805  6489.560059  6489.560059  ...  0.587100  6479.410156      0
1528968720  6487.370117  6489.560059  6489.549805  ...  7.706374  6479.979980      0
1528968780  6479.410156  6487.370117  6487.370117  ...  3.088252  6480.000000      1
1528968840  6479.410156  6479.419922  6479.419922  ...  1.404100  6477.220215      0
1528968900  6475.930176  6479.979980  6479.410156  ...  0.753000  6480.000000      1
1528968960  6477.959961  6480.000000  6477.959961  ...  1.490900  6479.990234      0
1528969020  6477.220215  6480.000000  6479.990234  ...  2.731950  6478.660156      1
1528969080  6477.220215  6480.000000  6477.220215  ...  2.174240  6478.660156      0
1528969140  6479.990234  6479.990234  6479.990234  ...  0.903100  6479.339844      0
1528969200  6477.259766  6479.990234  6479.990234  ...  3.258786  6479.350098      1

[10 rows x 7 columns]

In [25]:
scaled_data = scaler.fit_transform(btc_df[["Close", "Volume"]])
scaled_data

array([[0.26303937, 0.00073017],
       [0.26223709, 0.00961326],
       [0.25929046, 0.00385098],
       ...,
       [0.34565159, 0.00290609],
       [0.34570701, 0.00095824],
       [0.34621719, 0.00124867]])

In [26]:
scaled_data[:, 0]

array([0.26303937, 0.26223709, 0.25929046, ..., 0.34565159, 0.34570701,
       0.34621719])

In [27]:
scaled_data[:, 1]

array([0.00073017, 0.00961326, 0.00385098, ..., 0.00290609, 0.00095824,
       0.00124867])

In [ ]:
data = {}
data["Close"] = 